theme = "gruvbox"

[editor]
cursorline = true
rulers = [120]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.inline-diagnostics]
cursor-line = "error"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
"ret" = "goto_word"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
